#!/bin/bash
EWW="sh $HOME/.config/eww/scripts/run"

# First work
feh --bg-fill $HOME/.config/bspwm/images/wallpaper.jpg
$EWW bar start
$EWW menu start

xsetroot -cursor_name left_ptr
setxkbmap latam

sxhkd &

#                      STYLE

bspc config automatic_scheme spiral

bspc config -m HDMI-0 top_padding 33

bspc config border_width         2
bspc config window_gap           7
bspc config split_ratio           6 
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config focus_follows_pointer true

bspc config normal_border_color "#331641"
bspc config focused_border_color "#705192"
bspc config presel_feedback_color "#331641"

#monitor
bspc monitor HDMI-0 -d 1 2 3 4 5
bspc monitor VGA-0 -d 6 7 8 9 

#window rules
rule -a wezterm                     follow=on focus=on
rule -a Code                        follow=on focus=on
rule -a firefox                     follow=on focus=on
rule mpv                            state=floating
rule feh                            state=floating

#Notifications
#dunst

pkill picom
picom -f --daemon --config "${HOME}/.config/picom/picom.conf" &

$EWW bar open
#
#                     GENERAL CONFIGURATION                           #

bspc subscribe node_state | while read -r _ _ _ _ state flag; do
    if [ "$state" != "fullscreen" ]; then
        continue
    fi
    if [ "$flag" == on ]; then
        $EWW bar close
  else
        $EWW bar open
    fi
done &

bspc config pointer_modifier Alt	






